kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "ocean.fullname" . }}-raw-config"
  labels:
    {{- include "ocean.labels" . | nindent 4 }}
data:
  admin.txt: |
    {"email":"${ADMIN_EMAIL}","password":"${ADMIN_PASS}"}
