{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean.adminSecret" . }}
  labels:
    {{- include "ocean.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  EMAIL: {{ .Values.admin.email | b64enc | quote }}
{{- end }}
