{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean.databaseSecret" . }}
  labels:
    {{- include "ocean.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ .Values.database.password | b64enc | quote }}
  HOSTNAME: {{ .Values.database.hostname | b64enc | quote }}
{{- end }}
